### ISSUE TITLE
validate criticalRegionSize in Configuration.java

### ISSUE THREAD

**Issue by chanwangkiu** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#1]
![image](https://user-images.githubusercontent.com/32842145/99772295-7627f500-2b45-11eb-8e5b-ef8b9966a987.png)

The throw statement is capacity of critical region size for...
Are we validating criticalRegionSize? 
Or should we validate criticalRegionCapacity instead?

**Comment by Troublor** [comment]
You should validate both size and capacity of critical region. 
* `size`: critical region size should be an `odd` number, at least `1` and at most `size of game board - 2`
* `capacity`: critical region capacity should be at least `1` and at most `size of game board (max number of knights)`.

**Comment by Kelvinluk827** [comment]
but max number of knights = size +1

because size is odd and 
              number of knights per player = ceiling(size/2)
so number of knights per player = size/2 + 0.5

and there are 2 players
so max number of knights = (size/2 + 0.5) * 2 = size + 1

**Comment by Troublor** [comment]
> You should validate both size and capacity of critical region.
> 
> * `size`: critical region size should be an `odd` number, at least `1` and at most `size of game board - 2`
> * `capacity`: critical region capacity should be at least `1` and at most `size of game board (max number of knights)`.

Sorry I was talking about `max number of knights of each player`. The max number is `size` since we can put all knights in one row and no archers. 
Although, we require a specific piece arrangement in PA3. It is still possible to do that in PA1.

**Comment by zcmiyano** [comment]
Shouldn't the max size of the criticalRegionCapacity be the same as the size of the critical region rather than the board size?

**Comment by Troublor** [comment]
There are at most `board size` number of knights for each player. There is no point to set the max size of `criticalRegionCapacity` to the size of critical region.
