### ISSUE TITLE
GREEDY Behavior

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#13]
"The piece prefers to move towards the central place." May I ask how to calculate the distance here? I think we should use the Manhattan distance, right?

**Comment by Troublor** [comment]
Yes you can use Manhattan distance.

**Comment by tcchanan** [comment]
Also, we are only required to compare move.destination to the center coordinate right? what if there are the same distance results?

**Comment by Troublor** [comment]
Yes, GREEDY is greedy towards center coordinate. If there are multiple moves with same distance, randomly pick one is enough.
