### ISSUE TITLE
About calculateMoveParametersQueue

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#15]
The javadoc for `calculateMoveParametersQueue` suggests that parameters `Game` and `Place` should be passed in before the thread can run. However, `calculateMoveParametersQueue` is a private instance variable. Are we supposed to define public mutator methods that pass `Game` and `Place` into `calculateMoveParametersQueue`?

Thank you in advance for your attention.

**Comment by Troublor** [comment]
Refer to #11

**Comment by lky-bulbasaur** [comment]
Just to make sure, does this mean I am allowed to add whatever helper method I want?

Thanks.

**Comment by Troublor** [comment]
Yes you can. But don't change the arguments and return value type of any existing methods.
