### ISSUE TITLE
About terminate the piece thread

### ISSUE THREAD

**Issue by czhuai** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#16]
Every time we make a decision we will clear the calculateMoveParametersQueue, then if we want to terminate a piece thread, how can we access the thread in the terminate() function since we can't get the game from the calculateMoveParametersQueue?

**Comment by Troublor** [comment]
You have to figure it out yourself.
You can add any class fields/methods as you want to facilitate the implementation of functionalities, as long as you don't change the arguments and return type of existing functions.

**Comment by Troublor** [comment]
Existing class fields such as `calculateMoveParametersQueue` can be left not used, as long as the functionality is correct.

**Comment by czhuai** [comment]
And about pause, do I need to pause the thread in the pause()? I think we already make sure we pause it in the run().

**Comment by Troublor** [comment]
`pause()` method is called by the player to pause the thread. 
I don't quite get your point.

**Comment by czhuai** [comment]
I mean in pause() we change the running, then in run() we will pause the thread if running is false, right?

**Comment by Troublor** [comment]
Yes, that's correct

**Comment by czhuai** [comment]
And for getCandidateMove() function in knight

public synchronized Move getCandidateMove(Game game, Place source)

but I think this function has nothing to do with thread?

**Comment by Troublor** [comment]
This function is called from outside to get candidate move when it's the player's turn,
while candidate move is generated inside the thread. 
You need to fill the gap between thread and `getcandidateMove()`.

**Comment by czhuai** [comment]
Yes.
My idea is that in getCandidateMove() we will call run() to get the candidateMoveQueue filled, and we pause the thread in run(). Then I think I don't need this synchornized for getCandidateMove() if I put synchornized for run().

**Comment by Troublor** [comment]
run() is a method of Runnable() interface, which will be called automatically when the thread is started, i.e. when initializing the game board. 
It should not be called in `getCandidateMove()`

**Comment by czhuai** [comment]
You mean the run() in the Archer or Knight is called when initializing the game board?

**Comment by Troublor** [comment]
Yes we start all piece threads when initializing the game board, at this time, `run()` will be implicitly called.

**Comment by czhuai** [comment]
But then what does it maeans by the comments of run()?

![image](https://user-images.githubusercontent.com/61261586/101180198-3bb27200-3686-11eb-9eca-a85f485d0226.png)

if we call it when initializing why we need to consider this?

**Comment by czhuai** [comment]
Now I understand. Thanks for your help.

**Comment by zcmiyano** [comment]
> I mean in pause() we change the running, then in run() we will pause the thread if running is false, right?
> Yes, that's correct

May I ask what does pause the thread in run() mean here? Does it mean we don't propose candidateMove here? Or we really need to pause a thread?

**Comment by Troublor** [comment]
> > I mean in pause() we change the running, then in run() we will pause the thread if running is false, right?
> > Yes, that's correct
> 
> May I ask what does pause the thread in run() mean here? Does it mean we don't propose candidateMove here? Or we really need to pause a thread?

Redirect to #29
