### ISSUE TITLE
About CriticalRegionRule

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#17]
Suppose `criticalRegionSize = 1` and `criticalRegionCapacity = 1`, and I have a game like this:
![image](https://user-images.githubusercontent.com/61015577/101194848-812c6a80-3699-11eb-8162-358335e93c87.png)

If the Blue Knight (c5) captures the Green Knight (d3), will this move violate the critical region rule?

Thanks.

**Comment by Troublor** [comment]
I don't think so. Would you clarify your point?

**Comment by lky-bulbasaur** [comment]
In the picture shown, there is 1 Knight (Green) in the critical region.
If the Blue Knight (c5) captures the Green Knight (d3), there will still be 1 Knight (Blue) in the critical region.

Is my understanding correct?

**Comment by Troublor** [comment]
Yes, you are correct. Do you mean the problem is that: the capturing move is said to be violating the rule by the demo program?

**Comment by lky-bulbasaur** [comment]
After several attempts I was able to reproduce the game in question using the demo program, so I could finally verify the specification.

Closing this issue now. Thanks.
