### ISSUE TITLE
About "synchronized" key word

### ISSUE THREAD

**Issue by wuto-chai** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#18]
noticed that there is "synchronized" modifier in Knight's getCandidateMove but no in Archer's.
Are we supposed to implement implicit lock for Knight and explicit lock for Archer?
or can we add "synchronized" in Archer or delete it in Knight?

**Comment by Troublor** [comment]
You can delete or add `synchronized` modifier as you wish. 
It doesn't matter.

**Comment by wuto-chai** [comment]
what about add it in other methods?

**Comment by Troublor** [comment]
Yes you can add `synchronized` to other methods as well.

**Comment by wuto-chai** [comment]
thanks!
