### ISSUE TITLE
About Actions

### ISSUE THREAD

**Issue by czhuai** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#19]
If an action is applied to a piece which has been terminated, do I need to throw ActionException or just doing nothing is ok?

And for undo action, it it only undo the move or we need to undo pause and resume?

Thank you

**Comment by Troublor** [comment]
Throw ActionException showing the piece has been terminated

**Comment by Troublor** [comment]
Only undo the move.

**Comment by czhuai** [comment]
Understand. Thanks for your help.

**Comment by czhuai** [comment]
If I captured a pause piece A and then undo, it adds that captured piece A back. Then should piece A be paused?

**Comment by zcmiyano** [comment]
But in the demo, pausing a terminated piece will print the message "Action[Pause piece] performed"?

**Comment by Troublor** [comment]
> But in the demo, pausing a terminated piece will print the message "Action[Pause piece] performed"?

That is indeed a problem. A terminated piece cannot be paused.

**Comment by Kit-p** [comment]
What about pausing a paused piece? It works in the sample program as well.

**Comment by Troublor** [comment]
Well, the principle is that: 
* The consequence of `pause` actions is to prevent the piece from proposing more moves. 
* Since paused pieces already cannot propose moves, it doesn't matter if we pause it again. 
* It is the same with `pausing a terminated piece`, the consequence of `pause` is a subset of consequence of `terminate`, so  we didn't throw exceptions there either.

**Comment by Kit-p** [comment]
As you have replied in the first comment, "Throw ActionException showing the piece has been terminated", I would like to know does it mean I should also throw ActionException when the user tries to pause a paused piece?
Thank you in advance.

**Comment by Troublor** [comment]
No, keep it the same with the demo program, don't throw exception for `pause a paused piece` and `pause a terminated piece`.

**Comment by czhuai** [comment]
For undo, we can at most undo 3 times, is that means I can undo no more than 3 times, then make a move and again undo no more than 3 times?

**Comment by Troublor** [comment]
Consider you only have memory with capacity of three rounds. 
If you undo for 2 times and then make a move, now you can only undo 2 times now.

**Comment by czhuai** [comment]
I just try this on demo program.

First make 4 moves, the history is:

player:White; move:(1,0)->(1,1)
player:Black; move:(5,8)->(5,7)
player:White; move:(1,1)->(1,2)
player:Black; move:(5,7)->(0,7)
player:White; move:(1,2)->(1,3)
player:Black; move:(0,7)->(1,7)
player:White; move:(1,3)->(1,4)
player:Black; move:(6,8)->(4,7)

then undo 2 times

player:White; move:(1,0)->(1,1)
player:Black; move:(5,8)->(5,7)
player:White; move:(1,1)->(1,2)
player:Black; move:(5,7)->(0,7)

then make 1 move

player:White; move:(1,0)->(1,1)
player:Black; move:(5,8)->(5,7)
player:White; move:(1,1)->(1,2)
player:Black; move:(5,7)->(0,7)
player:White; move:(1,2)->(1,3)
player:Black; move:(4,8)->(6,7)

then undo

player:White; move:(1,0)->(1,1)
player:Black; move:(5,8)->(5,7)
player:White; move:(1,1)->(1,2)
player:Black; move:(5,7)->(0,7)
player:White; move:(1,2)->(1,3)

But this time it only undo the computer player move.

**Comment by Troublor** [comment]
Oh I confirm this is indeed a bug, which is also mentioned in #26. 
It should have been fixed by #28.

**Comment by zcmiyano** [comment]
It seems that we can also terminate a terminated piece and pause a terminated piece?

**Comment by Troublor** [comment]
> Well, the principle is that:
> 
> * The consequence of `pause` actions is to prevent the piece from proposing more moves.
> * Since paused pieces already cannot propose moves, it doesn't matter if we pause it again.
> * It is the same with `pausing a terminated piece`, the consequence of `pause` is a subset of consequence of `terminate`, so  we didn't throw exceptions there either.

Yeah, just as I stated in the quote. But if your implementation disallows pausing a terminated piece, it is fine. The tests will also consider it correct.

**Comment by Kelvinluk827** [comment]
> Consider you only have memory with capacity of three rounds.
> If you undo for 2 times and then make a move, now you can only undo 2 times now.

Does this mean we can in total undo 3 times in the whole game, or we can undo 3 consecutive times depending on that memory
Also is it allowed to have a implementation infinite undoes?

**Comment by Troublor** [comment]
You can at most do 3 consecutive times of `undo`. 

What do you mean by infinite `undo`es?

**Comment by Kelvinluk827** [comment]
for infinite undoes, I mean it is allowing the user to undo until it reaches the start of the game.
is this prohibited?

**Comment by Troublor** [comment]
No, infinite undo is prohibited.
