### ISSUE TITLE
Which of the tests are the regression tests?

### ISSUE THREAD

**Issue by Kelvinluk827** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#21]
As stated

**Comment by Troublor** [comment]
All those provided to you.

**Comment by ccCLCcc** [comment]
hi, may I know some more details about the TA-only tests? eg do they include both unit tests and integrated tests..

**Comment by Troublor** [comment]
TA-only tests include unit tests and integrated tests, but in PA3 this time we don't distinguish them.
