### ISSUE TITLE
More about Actions

### ISSUE THREAD

**Issue by Kit-p** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#22]
1. Currently in the demo program, I observe that only the first element in `args` are processed in `PaucePieceAction`, `ResumePieceAction` and `TermiantePieceAction`. May I know if that is the intended behavior?
For example:
`terminate a9 b9 c9`  only terminates the piece at `a9`.

2. In README.md, the terminate action usage states that we should use the actional word `stop`, which doesn't work in the demo program. Do we need to make `stop` an alias of `terminate`?

3. The `undo` action also takes `args`, it has no effect in the demo program, but do we need to make inputs like `undo 2` to undo 2 steps?

**Comment by Troublor** [comment]
1. You are right, demo program only implements `pause one at a time`.
2. It should be a typo. You should use `terminate`. 
3. `undo` takes no args and only undo the last human player's move.

**Comment by Kit-p** [comment]
Thank you for the reply!

**Comment by zcmiyano** [comment]
So we only need to pause one at a time?

**Comment by Troublor** [comment]
> So we only need to pause one at a time?

Yes, if your implementation also works for multiple arguments. That's also fine.
