### ISSUE TITLE
Critical Region

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#24]
<img width="646" alt="Screenshot 2020-12-07 at 4 02 24 PM" src="https://user-images.githubusercontent.com/35625778/101324742-ae4d6880-38a5-11eb-8c0c-d7860595b4de.png">
I used 5 1 1 1 to run the demo, two Knights can be in the critical region at the same time, is this a bug?

**Comment by zcmiyano** [comment]
Is it okay if I don't use the function "isInCriticalRegion(Game game, Place place)"?

**Comment by wuto-chai** [comment]
should be no i think since critical region rule is applied to each player (each player can have capacity number Knights in region)  not the whole game

**Comment by zcmiyano** [comment]
Yes, thank you
