### ISSUE TITLE
About TA-only test cases

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#25]
May I know that in TA-only test cases, will the thread states be checked using `getState()`? For example, when implementing `PausePieceAction`, I might not necessarily use the suggested `interrupt()` and `notifyAll()` to implement the same functionality. Will this affect the result of the TA-only tests?

Thanks.

**Comment by Troublor** [comment]
Where is the `getState()` method? I couldn't find it in the code skeleton.

**Comment by lky-bulbasaur** [comment]
From what I have Googled, `java.lang.Thread.getState()` can be used to check the state of a Thread. I wonder if this method will be used to strictly check the states of each thread in TA-only test cases.

**Comment by Troublor** [comment]
Oh, it is not used in tests.
