### ISSUE TITLE
About Undo operation

### ISSUE THREAD

**Issue by wuto-chai** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#26]
If computer player serves as the first player and human as second.
Is in round2 (human first round) doing undo same as let computer consider again and perform a new(or may not be new) move in round 1?

**Comment by zcmiyano** [comment]
I undo the game three times, and it undoes three turns, whereas after I make more moves and then undo, it will only undo one move each time in the demo.

**Comment by zcmiyano** [comment]
Can we undo 3 times then make a move then undo 3 times?

**Comment by wuto-chai** [comment]
can we modify other methods in order to achieve undo()?

**Comment by Troublor** [comment]
Undo is only performed when it's human player's turn. 
One `undo` results the game state back to the last time of human player to play. 
In other words, `undo` always undo the latest computer's move and then undo the latest human player's move.

**Comment by Troublor** [comment]
> Can we undo 3 times then make a move then undo 3 times?

No, consider the program has a memory which only has 3 slots of rounds, any older rounds will be forgotten. 
If we undo 3 times, all rounds stored in the slots have been consumed. 
And now we move again, there is only one round stored in the memory. 
So we can only undo once at this time.

**Comment by Troublor** [comment]
> can we modify other methods in order to achieve undo()?

Yes you can modify other methods, but do it as your own risk, since it is enough to only write code at `TODO`s. 

If you still want to modify other methods, please keep the signature of the methods unchanged, otherwise they will break the tests.

**Comment by zcmiyano** [comment]
> I undo the game three times, and it undoes three turns, whereas after I make more moves and then undo, it will only undo one move each time in the demo.

If I undo more than 3 times (with moves between) The undos after 3 times won't undo the computer move and the human move but will only undo one move. I think this is a bug.

**Comment by Troublor** [comment]
You are correct. 
I have just fixed it.

**Comment by wuto-chai** [comment]
would like to specify the question one again lol like  ( if computer is player1 and human player2 )

Round1---Computer
do a move
Round2---Human
Action : undo

in this case there is no last human move. so to what extent should we undo?

or human must be the first player so we need not consider it?

**Comment by wuto-chai** [comment]
or human must be the first player so we need not consider it?

**Comment by Troublor** [comment]
For simplicity, just consider human player will always be the first one to move.
