### ISSUE TITLE
Terminate action keyword clarification

### ISSUE THREAD

**Issue by SONGRENHE** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#27]
<img width="358" alt="Screen Shot 2020-12-07 at 9 56 26 PM" src="https://user-images.githubusercontent.com/55167937/101359374-26805200-38d7-11eb-8b4f-0f94b6c41a50.png">
in the obfuscated version to do action terminate it uses "terminate a3" instead of "stop a3", is it a bug? In the TA tests do you use stop a3?
Thanks!

**Comment by Kit-p** [comment]
Check latest commit and #22 .
