### ISSUE TITLE
Pause a thread

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#29]
> I mean in pause() we change the running, then in run() we will pause the thread if running is false, right?
> Yes, that's correct

May I ask what does pause the thread in run() mean here? Does it mean we don't propose candidateMove here? Or we really need to pause the thread from pieceThreadMap?

_Originally posted by @zcmiyano in https://github.com/CastleLab/COMP3021-2020Fall-PA3-Student-Version/issues/16#issuecomment-740064166_

**Comment by Troublor** [comment]
It just refers to `pause the piece`, which means the piece won't propose candidate moves anymore. What @zcmiyano said is related to his/her own implementation details.
