### ISSUE TITLE
Obfuscated Version Critical Region

### ISSUE THREAD

**Issue by DoVaKeitH** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#3]
![critical](https://user-images.githubusercontent.com/63578180/100228628-eb3c6580-2f5d-11eb-9499-f52aaaa4ee75.png)

I think there is a bug in the obfuscated version? as the critical region size is 3 and capacity is 2.

The situation in the picture showed should be invalid?

**Comment by Troublor** [comment]
The `capacity` refers to the max number of `Knights` of each player that are allowed in the critical region.
So it is valid here.

**Comment by DoVaKeitH** [comment]
Then I think the description about the capacity of the critical region need to be modified.
As the current description is "criticalRegionCapacity: the maximum number of pieces inside the critical region."

**Comment by Troublor** [comment]
Right, thanks for pointing out

**Comment by SONGRENHE** [comment]
<img width="619" alt="Screen Shot 2020-12-07 at 10 11 48 PM" src="https://user-images.githubusercontent.com/55167937/101360918-41ec5c80-38d9-11eb-9153-88dcb0d2f032.png">
Is this a bug in the obfuscated version? critical region size is 1 and capacity is 1. But black wins after I let my knight enter the critical region.
