### ISSUE TITLE
Code Style in TA's code

### ISSUE THREAD

**Issue by Kwok-Kai-Yin-Pollux** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#30]
Coding style is also part of the grading. Also, we are not recommended to change any codes unless specified in the hints.
However, there are some coding style violations in the TA's code, should I fix those myself?
Here are some of the errors:

1) `Name 'UNDO_LIMIT' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName] `
In `Game.java`
2) `switch without "default" clause. [MissingSwitchDefault]`
In `ConsolePlayer.java` `parseAction()`
3) a lot of unused imports
Would the TA only test fail if I remove the unused imports?

**Comment by Troublor** [comment]
Well, the tests only deals with methods and class. So as long as you keep the signature of methods (method name, arguments and return value) and class (class name, superclass and interface) unchanged, it will not affect the tests. 

So you can change `UNDO_LIMIT` to  others as you wish, you can also add default clause and remove unused imports.
