### ISSUE TITLE
Question about input format

### ISSUE THREAD

**Issue by ccCLCcc** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#31]
From the demo, if I input "terminate a1    0", it will terminate the piece a1.
Do i need to trim all spaces in between such that it is terminating a10 instead of a1? or just follow the demo version?

Also, from #19, so can I terminate a terminated piece again? Do I need to throw ActionException or I just follow the demo, showing "Action[Terminate piece] performed"?

**Comment by Troublor** [comment]
> From the demo, if I input "terminate a1 0", it will terminate the piece a1.
> Do i need to trim all spaces in between such that it is terminating a10 instead of a1? or just follow the demo version?

No need to trim the spaces between characters. Just trim spaces in the beginning and the tail. 
You can just follow the demo version.

> Also, from #19, so can I terminate a terminated piece again? Do I need to throw ActionException or I just follow the demo, showing "Action[Terminate piece] performed"?

No need to throw ActionException, just follow the demo.

**Comment by ccCLCcc** [comment]
Thanks!
