### ISSUE TITLE
About running variable in knight and archer

### ISSUE THREAD

**Issue by ywucr** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#36]
From the comment of the variable "running", we can know that "running" is used to mark if the thread is running or paused.
![image](https://user-images.githubusercontent.com/56708723/101458127-6f84e480-3971-11eb-902f-f035a0634fab.png)

But the comment of method run() (as shown below) means we use "running" to mark if it is the turn of the player.
Is it mean that if not the player's turn we should pause all the player's pieces, and resume all the pieces until his turn?
![image](https://user-images.githubusercontent.com/56708723/101457993-3482b100-3971-11eb-9c2f-af131f7d4166.png)

**Comment by Troublor** [comment]
You misunderstand the JavaDoc in `run()` method. It means only propose move when `running = true`;

**Comment by ywucr** [comment]
Got it. Thanks
