### ISSUE TITLE
Non-deterministic vs Random

### ISSUE THREAD

**Issue by Kelvinluk827** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#37]
Does non-deterministic count as random? As in my implementation to choose move randomly, I did that with the concise code `.parallelStream().findAny()`, which is said to be non-deterministic.

**Comment by Troublor** [comment]
Non-deterministic is different. 
By `random` we refer to uniformly distributed random, but non-determinism is not necessarily uniformly distributed.

**Comment by Kelvinluk827** [comment]
ok thx
