### ISSUE TITLE
Two questions about spec

### ISSUE THREAD

**Issue by Kwok-Kai-Yin-Pollux** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#40]
What should getAvailableMoves() in JesonMor return?
https://github.com/CastleLab/COMP3021-2020Fall-PA3-Student-Version#jesonmor
Quote
`If current player is computer player: return an array containing only ONE move selected from all available moves.`
Does this mean one move for each piece, i.e. when there are 5 knights 4 archers for black computer player, return an array of size 9?
It does not make sense to return an array of size ONE since the picking of the move is done in `player.nextMove()` which will call `MakeMoveByBehavior.getNextMove()`.

Also, am I allowed to add in new `Behavior` for the `SMART Strategy`? I am planning to add a smarter greedy behavior and add this behavior to the `Behavior` enum class, and use this behavior in the `SmartPlayerFactory`. However, the spec does not seems to say whether I can do so.

**Comment by Troublor** [comment]
> What should getAvailableMoves() in JesonMor return?
> https://github.com/CastleLab/COMP3021-2020Fall-PA3-Student-Version#jesonmor
> Quote
> `If current player is computer player: return an array containing only ONE move selected from all available moves.`
> Does this mean one move for each piece, i.e. when there are 5 knights 4 archers for black computer player, return an array of size 9?
> It does not make sense to return an array of size ONE since the picking of the move is done in `player.nextMove()` which will call `MakeMoveByBehavior.getNextMove()`.

Yes, one move for each piece belonging to the player. Your example is correct, return an array of size 9.  


> Also, am I allowed to add in new `Behavior` for the `SMART Strategy`? I am planning to add a smarter greedy behavior and add this behavior to the `Behavior` enum class, and use this behavior in the `SmartPlayerFactory`. However, the spec does not seems to say whether I can do so.

Yes you can add more enums in `Behaviour` class, but don't delete any existing enums and make sure they are implemented as required.
