### ISSUE TITLE
Question about JesonMor.getAvailableMoves()

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#45]
I have a question related to #40 .

For `ComputerPlayer`, the expected size of the returned array = the number of `ComputerPlayer`'s pieces on the board.
For example, if the `ComputerPlayer` has 5 pieces, then `JesonMor.getAvailableMoves()` should return a Move array of size 5. However, if a piece proposed null due to being paused/terminated/not having available moves, should the size of the returned array be 4 instead?

Thanks.

**Comment by Troublor** [comment]
Yes, it should exclude the paused/terminated pieces.
