### ISSUE TITLE
Weird behavior in TA-only tests

### ISSUE THREAD

**Issue by Xelopie** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#46]
I think there are probably some bugs in TA-only tests. Not sure why it is happening but it is kinda weird. 
I discovered them by adding the line "game.refreshOutput();" below every "var game = new JesonMor(config);"

Originally I failed the testPieceGetCandidateMove() in PieceTests(), but after I did this, I passed the tests.
![image](https://user-images.githubusercontent.com/47631876/102991326-f500bb00-4553-11eb-81e8-734efb172e64.png)

Because in the real game flow, we need to call refreshOutput() in JesonMor::start(). And my implementation is working fine in the real game flow but failed in tests. So I am curious if this is some kinda bugs. refreshOutput() shouldn't have modified any variables in game

**Comment by Troublor** [comment]
You are making a mistake by adding `synchronized` keyword to `getCandidateMove` method, which induce data race between `getCandidateMove` method and `synchronized(this){...}` inside `run()` method. 
When the testing is running, if `getCandidateMove` is called first, it will hold the lock of `this`, which prohibits the thread to go into `synchronized(this){...}` and deadlock there until 1 sec timeout.

**Comment by Xelopie** [comment]
oic, really thanks for pointing that out. That deadlock problem is hard to discover
