### ISSUE TITLE
About isWhite/BlackPlayerHuman in Configuration class

### ISSUE THREAD

**Issue by leiyi777** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#5]
In the readme, it says that there are other types of HumanPlayer in TA-only tests so we need to use "instanceof HumanPlayer" to check whether this player is a human player or not. 
However, the isWhite/BlackPlayerHuman methods in Configuration class just use "instanceof ConsolePlayer" to check the type.
Do I need to change the already implemented methods to "instanceof HumanPlayer"?

**Comment by Troublor** [comment]
Those methods are legacy of PA2. Should be removed from PA3.
