### ISSUE TITLE
getAvailableMoves in JesonMor.java

### ISSUE THREAD

**Issue by ks602** [CastleLab/COMP3021-2020Fall-PA3-Student-Version#8]
I don't understand the requirement of returning only one move in getAvailableMoves
It is stated in the comment that
`- for {@link ComputerPlayer}:
    ...
      return an array containing only ONE move selected from all available moves`
The returned available moves will then be passed to Player.nextMove()
When the Player is a Computer Player, nextMove returns
`return new MakeMoveByStrategy(game, availableMoves, this.strategy).getNextMove();`
but the availableMoves we passed in contains only one move, then the getNextMove in MakeMoveByStrategy makes no sense.

**Comment by Troublor** [comment]
You are correct, this statement about `getAvailableMoves()` is wrong. 
It should be `return an array containing candidate moves from each piece of computer player which are not paused or terminated`.
